corpus:
  -
    regexp: "(CQ:at,qq=2393827810.*)?/ping"
    reply: "正在 Ping 114.514.19.19 具有 810 字节的数据:"
    scene: "a"
    delay: 0.1
  -
    regexp: "(CQ:at,qq=2393827810.*)?/ping"
    reply: "请求超时。"
    scene: "a"
    delay: 4.9
  -
    regexp: "corpus3"
    reply: "delay: 5s"
    scene: "a"
    delay: 5
  -
    regexp: "龙图"
    reply: 
      - "[CQ:image,file=../long/AAQARGUGRBAQ.jpg]"
      - "[CQ:image,file=../long/ACUJRGGOVGFB.jpg]"
      - "[CQ:image,file=../long/AFMJHFTOVSPAEK.jpg]"
      - "[CQ:image,file=../long/ALEJDQJRMU.jpg]"
      - "[CQ:image,file=../long/ANRETTZJKOH.png]"
    scene: "a"
    delay: 
  -
    regexp: "所有场景"
    reply: "a"
    scene: "a"
    delay: 
  -
    regexp: "群聊场景"
    reply: "g"
    scene: "g"
    delay: 
  -
    regexp: "私聊场景"
    reply: "p"
    scene: "p"
    delay: 
  -
    regexp: "delay"
    reply: "0"
    scene: "p"
    delay: 
  -
    regexp: "delay"
    reply: "0.1"
    scene: "p"
    delay: 0.1
  -
    regexp: "delay"
    reply: "0.2"
    scene: "p"
    delay: 0.2
  -
    regexp: "delay"
    reply: "0.3"
    scene: "p"
    delay: 0.3
  -
    regexp: "delay"
    reply: "0.4"
    scene: "p"
    delay: 0.4
  -
    regexp: "delay"
    reply: "0.5"
    scene: "p"
    delay: 0.5