main: #除特殊标注以外是冷更新
  websocket: "ws://127.0.0.1:9820" #go-cqhttp
  superUsers:  #int / []int
  #控制台日志等级，越大输出越多
  #Panic = 0
  #Fatal = 1
  #Error = 2
  #Warn  = 3
  #Info  = 4
  #Debug = 5
  #Trace = 6
  logLevel: 4
  ban: #热更新
    private:
      - 
    group:
      -
corpus: #热更新
# - #模板
#   regexp: "" #正则表达式
#   reply: "" #回复内容  string / []string / forwardNode
#   scene: "" #触发场景 "a"/"all" / "g"/"group" / "p"/"private"
#   delay:  #延迟回复（秒）  支持小数
#   [*]: reply内自定义消息转发节点属性(name(显示昵称), uin(头像))时，content也可以是[]string，等价于连着好几条同属性的消息节点
  -
    regexp: "(CQ:at,qq=.*)?/ping"
    reply: "正在 Ping 114.514.19.19 具有 810 字节的数据:"
    scene: "a"
    delay: 0.1
  -
    regexp: "(CQ:at,qq=.*)?/ping"
    reply: "请求超时。"
    scene: "a"
    delay: 4.9
  -
    regexp: "^所有场景$"
    reply: "all"
    scene: "all"
  -
    regexp: "^群聊场景$"
    reply: "group"
    scene: "group"
  -
    regexp: "^私聊场景$"
    reply: "private"
    scene: "private"
  -
    regexp: "^一条合并转发$"
    reply:
      - 第一句话
      - 第二句话
    scene: "a"
  -
    regexp: "^一条很牛逼的合并转发$"
    reply:
      - "111"
      - 222
      -
        name: "不是QQ小冰"
        uin: 2854196306
        content:
          - "彳亍"
          - "笑死"
      - 彳亍
      - "[CQ:reply,qq=2854196306,text=000]333"
    scene: "all"
qianfan: #热更新
  #https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Nlks5zkzu
  #留空fallback至glm
  #"ERNIE_Bot", "ERNIE_Bot_turbo", "BLOOMZ_7B"
  #"Llama_2_7b", "Llama_2_13b", "Llama_2_70b"
  model: "ERNIE_Bot"
  keys:
    api: ""
    secret: ""
parse: #热更新
  settings:
    #"glm", "qianfan"
    summaryBackend: "glm"
    #同一会话重复解析同一链接的间隔（秒）
    sameParseInterval: 60
    #过长的视频简介保留长度（中英字符）
    descTruncationLength: 32
push: #热更新
  settings:
    livePushMinimumInterval: 300 #同一直播间多次开播推送的最小间隔（秒）  用于解决某些主播因网络问题频繁重新推流导致多次推送
    dynamicUpdateInterval: 3 #拉取更新间隔（秒）
    resetCheckInterval: 15 #直播监听重连检测间隔（秒）
    roomChangeInfo: false #直播监控推送房间名更新（如果主播开播同时改房间名会导致推送两条）
    #通过拉取动态流进行推送，必须设置B站cookie，且需要关注想要推送的up
    cookie: ""
  list:
  # - #模板
  # uid: #up的uid  int ONLY
  # live: #up的直播间号，存在则监听并推送直播  int ONLY
  # user: #推送到的用户  int / []int
  # group: #推送到的群组  int / []int
  # at: #推送到群组时消息末尾at的人  int / []int    --------（有点鸡肋，之后想想怎么改又能不用群号当键）
  # filter: #此键存在内容时仅推送包含在内的动态类型（白名单） []string
  #     - "DYNAMIC_TYPE_WORD" #文本动态（包括投票/预约）
  #     - "DYNAMIC_TYPE_DRAW" #图文动态（包括投票/预约）
  #     - "DYNAMIC_TYPE_AV" #视频投稿（包括动态视频）
  #     - "DYNAMIC_TYPE_ARTICLE" #文章投稿
    - #謬纱特
      uid: 59442895
      live: 4626545
      group:
        - 
    - #岁己SUI
      uid: 1954091502
      live: 25788785
      group: 
        - 
        - 
    - #神崎 • H • 亚里亚
      uid: 898411
      live: 21949
      group: 
      filter:
      - "DYNAMIC_TYPE_WORD"
      - "DYNAMIC_TYPE_DRAW"
      - "DYNAMIC_TYPE_ARTICLE"